apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deploy
  namespace: gitlab
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-deploy-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-deploy-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-deploy-rb
  namespace: gitlab
subjects:
  - kind: ServiceAccount
    name: gitlab-deploy
    namespace: gitlab
roleRef:
  kind: ClusterRole
  name: gitlab-deploy-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-deploy-crb
subjects:
  - kind: ServiceAccount
    name: gitlab-deploy
    namespace: gitlab
roleRef:
  kind: ClusterRole
  name: gitlab-deploy-cluster-role
  apiGroup: rbac.authorization.k8s.io
